-- KHÓA HỌC
CREATE SEQUENCE SEQ_KHOAHOC
START WITH 1
INCREMENT BY 1
NOCACHE;
/
ALTER TABLE KetQuaHocTap ADD ( -- thiếu cột, thêm
    DU_DK_THITOTNGHIEP NUMBER(1),
    DAUTOTNGHIEP NUMBER(1),
    DU_DK_THISATHACH NUMBER(1),
    THOIGIANCAPNHAT DATE DEFAULT SYSDATE
);
/
ALTER TABLE KetQuaHocTap RENAME COLUMN soBuoiVang TO soBuoiToiThieu; -- sai tên cột, đổi tên
/
/* Thêm cột KmToiThieu */
ALTER TABLE KetQuaHocTap
ADD KmToiThieu NUMBER;

/* Đổi kiểu soKmHoanThanh sang NUMBER */
ALTER TABLE KetQuaHocTap
MODIFY soKmHoanThanh NUMBER;




/* HANGID = 1 */
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), -4), ADD_MONTHS(TRUNC(SYSDATE), -2), N'Trung tâm - Sân 1');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), -1), ADD_MONTHS(TRUNC(SYSDATE), 1), N'Trung tâm - Sân 2');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), -1)+5, ADD_MONTHS(TRUNC(SYSDATE), 1)+5, N'Trung tâm - Sân 3');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), -1)+10, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, N'Trung tâm - Sân 4');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, ADD_MONTHS(TRUNC(SYSDATE), 3)+10, N'Trung tâm - Sân 5');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), 1)+20, ADD_MONTHS(TRUNC(SYSDATE), 3)+20, N'Trung tâm - Sân 6');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), 1)+30, ADD_MONTHS(TRUNC(SYSDATE), 3)+30, N'Trung tâm - Sân 7');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), 1)+40, ADD_MONTHS(TRUNC(SYSDATE), 3)+40, N'Trung tâm - Sân 8');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), 1)+50, ADD_MONTHS(TRUNC(SYSDATE), 3)+50, N'Trung tâm - Sân 9');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (1, ADD_MONTHS(TRUNC(SYSDATE), 1)+60, ADD_MONTHS(TRUNC(SYSDATE), 3)+60, N'Trung tâm - Sân 10');

/* HANGID = 2 */
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), -4), ADD_MONTHS(TRUNC(SYSDATE), -2), N'Trung tâm - Sân A');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), -1), ADD_MONTHS(TRUNC(SYSDATE), 1), N'Trung tâm - Sân B');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), -1)+5, ADD_MONTHS(TRUNC(SYSDATE), 1)+5, N'Trung tâm - Sân C');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), -1)+10, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, N'Trung tâm - Sân D');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, ADD_MONTHS(TRUNC(SYSDATE), 3)+10, N'Trung tâm - Sân E');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), 1)+20, ADD_MONTHS(TRUNC(SYSDATE), 3)+20, N'Trung tâm - Sân F');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), 1)+30, ADD_MONTHS(TRUNC(SYSDATE), 3)+30, N'Trung tâm - Sân G');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), 1)+40, ADD_MONTHS(TRUNC(SYSDATE), 3)+40, N'Trung tâm - Sân H');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), 1)+50, ADD_MONTHS(TRUNC(SYSDATE), 3)+50, N'Trung tâm - Sân I');
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (2, ADD_MONTHS(TRUNC(SYSDATE), 1)+60, ADD_MONTHS(TRUNC(SYSDATE), 3)+60, N'Trung tâm - Sân K');

/* HANGID = 3 */
INSERT INTO KhoaHoc (hangId, ngayBatDau, ngayKetThuc, diaDiem) VALUES (3, ADD_MONTHS(TRUNC(SYSDATE), -4), ADD_MONTHS(TRUNC(SYSDATE), -2), N'Trung tâm - Sân 1');
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1), ADD_MONTHS(TRUNC(SYSDATE), 1), N'Trung tâm - Sân 2', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+5, ADD_MONTHS(TRUNC(SYSDATE), 1)+5, N'Trung tâm - Sân 3', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+10, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, N'Trung tâm - Sân 4', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, ADD_MONTHS(TRUNC(SYSDATE), 3)+10, N'Trung tâm - Sân 5', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+20, ADD_MONTHS(TRUNC(SYSDATE), 3)+20, N'Trung tâm - Sân 6', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+30, ADD_MONTHS(TRUNC(SYSDATE), 3)+30, N'Trung tâm - Sân 7', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+40, ADD_MONTHS(TRUNC(SYSDATE), 3)+40, N'Trung tâm - Sân 8', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+50, ADD_MONTHS(TRUNC(SYSDATE), 3)+50, N'Trung tâm - Sân 9', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 3, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+60, ADD_MONTHS(TRUNC(SYSDATE), 3)+60, N'Trung tâm - Sân 10', NULL);

/* HANGID = 4 */
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), -4), ADD_MONTHS(TRUNC(SYSDATE), -2), N'Trung tâm - Sân A', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1), ADD_MONTHS(TRUNC(SYSDATE), 1), N'Trung tâm - Sân B', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+5, ADD_MONTHS(TRUNC(SYSDATE), 1)+5, N'Trung tâm - Sân C', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+10, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, N'Trung tâm - Sân D', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, ADD_MONTHS(TRUNC(SYSDATE), 3)+10, N'Trung tâm - Sân E', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+20, ADD_MONTHS(TRUNC(SYSDATE), 3)+20, N'Trung tâm - Sân F', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+30, ADD_MONTHS(TRUNC(SYSDATE), 3)+30, N'Trung tâm - Sân G', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+40, ADD_MONTHS(TRUNC(SYSDATE), 3)+40, N'Trung tâm - Sân H', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+50, ADD_MONTHS(TRUNC(SYSDATE), 3)+50, N'Trung tâm - Sân I', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 4, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+60, ADD_MONTHS(TRUNC(SYSDATE), 3)+60, N'Trung tâm - Sân K', NULL);

/* HANGID = 5 */
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), -4), ADD_MONTHS(TRUNC(SYSDATE), -2), N'Trung tâm - Sân 1', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1), ADD_MONTHS(TRUNC(SYSDATE), 1), N'Trung tâm - Sân 2', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+5, ADD_MONTHS(TRUNC(SYSDATE), 1)+5, N'Trung tâm - Sân 3', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+10, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, N'Trung tâm - Sân 4', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, ADD_MONTHS(TRUNC(SYSDATE), 3)+10, N'Trung tâm - Sân 5', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+20, ADD_MONTHS(TRUNC(SYSDATE), 3)+20, N'Trung tâm - Sân 6', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+30, ADD_MONTHS(TRUNC(SYSDATE), 3)+30, N'Trung tâm - Sân 7', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+40, ADD_MONTHS(TRUNC(SYSDATE), 3)+40, N'Trung tâm - Sân 8', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+50, ADD_MONTHS(TRUNC(SYSDATE), 3)+50, N'Trung tâm - Sân 9', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 5, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+60, ADD_MONTHS(TRUNC(SYSDATE), 3)+60, N'Trung tâm - Sân 10', NULL);

/* HANGID = 6 */
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), -4), ADD_MONTHS(TRUNC(SYSDATE), -2), N'Trung tâm - Sân A', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1), ADD_MONTHS(TRUNC(SYSDATE), 1), N'Trung tâm - Sân B', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+5, ADD_MONTHS(TRUNC(SYSDATE), 1)+5, N'Trung tâm - Sân C', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+10, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, N'Trung tâm - Sân D', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, ADD_MONTHS(TRUNC(SYSDATE), 3)+10, N'Trung tâm - Sân E', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+20, ADD_MONTHS(TRUNC(SYSDATE), 3)+20, N'Trung tâm - Sân F', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+30, ADD_MONTHS(TRUNC(SYSDATE), 3)+30, N'Trung tâm - Sân G', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+40, ADD_MONTHS(TRUNC(SYSDATE), 3)+40, N'Trung tâm - Sân H', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+50, ADD_MONTHS(TRUNC(SYSDATE), 3)+50, N'Trung tâm - Sân I', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 6, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+60, ADD_MONTHS(TRUNC(SYSDATE), 3)+60, N'Trung tâm - Sân K', NULL);

/* HANGID = 7 */
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), -4), ADD_MONTHS(TRUNC(SYSDATE), -2), N'Trung tâm - Sân 11', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1), ADD_MONTHS(TRUNC(SYSDATE), 1), N'Trung tâm - Sân 12', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+5, ADD_MONTHS(TRUNC(SYSDATE), 1)+5, N'Trung tâm - Sân 13', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), -1)+10, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, N'Trung tâm - Sân 14', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+10, ADD_MONTHS(TRUNC(SYSDATE), 3)+10, N'Trung tâm - Sân 15', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+20, ADD_MONTHS(TRUNC(SYSDATE), 3)+20, N'Trung tâm - Sân 16', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+30, ADD_MONTHS(TRUNC(SYSDATE), 3)+30, N'Trung tâm - Sân 17', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+40, ADD_MONTHS(TRUNC(SYSDATE), 3)+40, N'Trung tâm - Sân 18', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+50, ADD_MONTHS(TRUNC(SYSDATE), 3)+50, N'Trung tâm - Sân 19', NULL);
INSERT INTO KhoaHoc VALUES (DEFAULT, 7, NULL, ADD_MONTHS(TRUNC(SYSDATE), 1)+60, ADD_MONTHS(TRUNC(SYSDATE), 3)+60, N'Trung tâm - Sân 20', NULL);











commit;