-- KHÓA HỌC
CREATE SEQUENCE SEQ_KHOAHOC
START WITH 1
INCREMENT BY 1
NOCACHE;
/
ALTER TABLE KetQuaHocTap ADD (
    DU_DK_THITOTNGHIEP NUMBER(1),
    DAUTOTNGHIEP NUMBER(1),
    DU_DK_THISATHACH NUMBER(1),
    THOIGIANCAPNHAT DATE DEFAULT SYSDATE
);
