create or replace PROCEDURE PROC_GET_USERS (
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            u.userId,
            u.userName,
            u.isActive,
            r.roleName,
            hv.hoTen,
            hv.sdt,
            hv.email
        FROM "User" u
        JOIN "Role" r ON u.roleId = r.roleId
        LEFT JOIN HocVien hv ON u.userId = hv.userId
        ORDER BY u.userId;
END;
/

create or replace PROCEDURE PROC_GET_USER_DETAIL (
    p_userId IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            u.userId,
            u.userName,
            u.isActive,
            u.roleId,
            r.roleName,
            hv.hocVienId,
            hv.hoTen,
            hv.soCmndCccd,
            hv.namSinh,
            hv.gioiTinh,
            hv.sdt,
            hv.email,
            hv.avatarUrl
        FROM "User" u
        JOIN "Role" r ON u.roleId = r.roleId
        LEFT JOIN HocVien hv ON u.userId = hv.userId
        WHERE u.userId = p_userId;
END;
/

create or replace PROCEDURE PROC_UPDATE_USER
(
    p_userId IN NUMBER,
    p_userName IN NVARCHAR2,
    p_isActive IN NUMBER,
    p_hoTen IN NVARCHAR2,
    p_sdt IN NVARCHAR2,
    p_email IN NVARCHAR2
)
AS
BEGIN
    UPDATE "User"
    SET userName = p_userName,
        isActive = p_isActive
    WHERE userId = p_userId;
END;
/
CREATE OR REPLACE PROCEDURE PROC_UPDATE_USER
(
    p_userId IN NUMBER,
    p_userName IN NVARCHAR2,
    p_isActive IN NUMBER,
    p_hoTen IN NVARCHAR2,
    p_sdt IN NVARCHAR2,
    p_email IN NVARCHAR2
)
AS
BEGIN
    UPDATE "User"
    SET userName = p_userName,
        isActive = p_isActive
    WHERE userId = p_userId;
END;
/

CREATE OR REPLACE PROCEDURE PROC_UPDATE_ROLE_SECURE
(
    p_userId IN NUMBER,
    p_roleId IN NUMBER,
    p_adminUser IN NVARCHAR2,
    p_adminPassword IN NVARCHAR2,
    o_result OUT NUMBER
)
AS
    v_password NVARCHAR2(200);
BEGIN
    -- lấy password admin
    SELECT "password"
    INTO v_password
    FROM "User"
    WHERE userName = p_adminUser;

    -- kiểm tra password (tạm so sánh thẳng)
    IF v_password != p_adminPassword THEN
        o_result := -1;
        RETURN;
    END IF;

    -- update role
    UPDATE "User"
    SET roleId = p_roleId
    WHERE userId = p_userId;

    o_result := 1;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        o_result := -2;
END;
/

CREATE TABLE PendingRegister (
    pendingId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    userName NVARCHAR2(100) NOT NULL,
    "password" NVARCHAR2(255) NOT NULL,
    email NVARCHAR2(100) NOT NULL,
    roleId NUMBER NOT NULL,
    otpCode NVARCHAR2(10) NOT NULL,
    expiredAt DATE NOT NULL,
    isUsed NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT pk_PendingRegister PRIMARY KEY (pendingId),
    CONSTRAINT ck_PendingRegister_isUsed CHECK (isUsed IN (0,1))
);
/

CREATE OR REPLACE PROCEDURE PROC_GET_USER_PROFILE
(
    p_userId IN NUMBER,
    o_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN o_cursor FOR
        SELECT
            u.userId      AS USERID,
            hv.hocVienId  AS HOCVIENID,
            u.userName    AS USERNAME,
            hv.email      AS EMAIL,
            hv.hoTen      AS HOTEN,
            hv.soCmndCccd AS SOCMNDCCCD,
            hv.namSinh    AS NAMSINH,
            hv.gioiTinh   AS GIOITINH,
            hv.sdt        AS SDT,
            hv.avatarUrl  AS AVATARURL
        FROM "User" u
        LEFT JOIN HocVien hv ON hv.userId = u.userId
        WHERE u.userId = p_userId;
END;
/


CREATE OR REPLACE PROCEDURE PROC_UPDATE_USER_PROFILE
(
    p_userId       IN NUMBER,
    p_username     IN NVARCHAR2,
    p_email        IN NVARCHAR2,
    p_hoTen        IN NVARCHAR2,
    p_soCmndCccd   IN NVARCHAR2,
    p_namSinh      IN DATE,
    p_gioiTinh     IN NVARCHAR2,
    p_sdt          IN NVARCHAR2,
    p_avatarUrl    IN NVARCHAR2,
    o_result       OUT NUMBER
)
AS
    v_count NUMBER;
BEGIN
    -- check username trùng người khác
    SELECT COUNT(*) INTO v_count
    FROM "User"
    WHERE userName = p_username
      AND userId <> p_userId;

    IF v_count > 0 THEN
        o_result := -1;
        RETURN;
    END IF;

    -- check email trùng người khác
    SELECT COUNT(*) INTO v_count
    FROM HocVien
    WHERE email = p_email
      AND userId <> p_userId;

    IF v_count > 0 THEN
        o_result := -2;
        RETURN;
    END IF;

    UPDATE "User"
    SET userName = p_username
    WHERE userId = p_userId;

    UPDATE HocVien
    SET email = p_email,
        hoTen = p_hoTen,
        soCmndCccd = p_soCmndCccd,
        namSinh = p_namSinh,
        gioiTinh = p_gioiTinh,
        sdt = p_sdt,
        avatarUrl = p_avatarUrl
    WHERE userId = p_userId;

    o_result := 1;
END;
/


COMMIT;

